/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./src/components/sectionBottom/BottomNav.vue')['default']
    ContextProvider: typeof import('./src/components/ContextProvider.vue')['default']
    DataEntryList: typeof import('./src/components/sectionMiddle/DataEntryList.vue')['default']
    DataTable: typeof import('./src/components/sectionMiddle/DataTable.vue')['default']
    DisaggregationForm: typeof import('./src/components/sectionMiddle/DisaggregationForm.vue')['default']
    IMaterialSymbolsSwapHoriz: typeof import('~icons/material-symbols/swap-horiz')['default']
    InitDataLoader: typeof import('./src/components/InitDataLoader.vue')['default']
    MainBody: typeof import('./src/components/sectionMiddle/MainBody.vue')['default']
    SelectorClear: typeof import('./src/components/sectionTop/SelectorClear.vue')['default']
    SelectorDataEntryToggle: typeof import('./src/components/sectionTop/SelectorDataEntryToggle.vue')['default']
    SelectorLocation: typeof import('./src/components/sectionTop/SelectorLocation.vue')['default']
    SelectorPeriod: typeof import('./src/components/sectionTop/SelectorPeriod.vue')['default']
    Selectors: typeof import('./src/components/sectionTop/Selectors.vue')['default']
    TopNav: typeof import('./src/components/sectionTop/TopNav.vue')['default']
  }
}
